name: Node.js Package

on:
  push:
    branches:
      - main
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@DanMM7'  
      - run: npm install
      - run: npm cache clean --force
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.MY_SECRET_KEY}}
